### ISSUE TITLE
No longer works in VS Code 1.7.0 due to deprecated code. Error msg below

### ISSUE THREAD

**Issue by JasonC66** [vstirbu/fsm-viewer#15]
Extension 'vstirbu.fsm-viewer' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by vstirbu** [comment]
fixed in 3ad6dacc396b25eafd2985de03bff9073c29de63
